POST http://localhost:3000/user/register
Content-Type: application/json

{
    "username": "yanky1",
    "email": "yankyhermawan421@gmail.com",
    "name": "yanky",
    "password": "abc123"
}
#### LOGIN ####
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "yanky",
    "password": "abcd1234"
}

#### GET ALL USER ####
GET http://localhost:3000/user
Content-Type: application/json

{
    "id": 1
}

### GET ALL USER ###
GET http://localhost:3000/user/all

### CHECK TOKEN VALID ###
GET http://localhost:3000/user/check-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ5YW5reSIsImlhdCI6MTczMjk4MjU2OSwiZXhwIjoxNzMzNTg3MzY5fQ.T1If4pIJ0Z5bi6zE2K1C3PrvwawJSnno2HETg9lQecQ

### GENERATE OTP ###
POST http://localhost:3000/user/otp
Content-Type: application/json

{
    "username": "yanky1"
}

### CHANGE PASSWORD ###
POST http://localhost:3000/user/forgetpassword
Content-Type: application/json

{
    "username": "yanky",
    "otp_number": 738720,
    "new_password": "abcd1234"
}

############################### COMPANY #############################
POST http://localhost:3000/company/create
Content-Type: application/json

{
    "name": "Moving Bytes",
    "user_id": 1
}

### GET ONE COMPANY ###
GET http://localhost:3000/company
Content-Type: application/json

{
    "id": 1
}

### MATERIAL ###
GET http://localhost:3000/material/all

### MAP ###
POST http://localhost:3000/map/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ5YW5reSIsImlhdCI6MTczMjk4MjU2OSwiZXhwIjoxNzMzNTg3MzY5fQ.T1If4pIJ0Z5bi6zE2K1C3PrvwawJSnno2HETg9lQecQ